---

image: maven:3.6.2-jdk-11-slim

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - deploy

build:
  stage: build
  only:
    refs:
      - master
      - /^feature.*/
  except:
    - tags
  script:
    - mvn ${MAVEN_CLI_OPTS} clean package
    - mvn exec:java -Dexec.mainClass=com.marlo.games.WordPuzzleApp
    - java -jar target/com.marlo.games.1.0.1.jar -s 4 -m c -l adevcrsoi
  artifacts:
    paths:
      - target

pages:
  stage: deploy
  only:
    refs:
      - master
  except:
    - tags
  script:
    - mvn $MAVEN_CLI_OPTS verify javadoc:javadoc site
    - mv target/site public
  artifacts:
    paths:
      - public
      - target/*.jar
