---

name: build java project using maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: set up jdk 1.11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11

      - name: build with maven
        run: mvn clean install
